FROM bellsoft/liberica-openjdk-alpine
COPY ./urlshortener-0.0.1-SNAPSHOT.jar /usr/app/
RUN chmod +x /usr/app/urlshortener-0.0.1-SNAPSHOT.jar
WORKDIR /usr/app
RUN apk add --no-cache curl tar bash procps nano vim
COPY wait-for-it.sh /usr/app
RUN chmod +x /usr/app/wait-for-it.sh
COPY docker-entrypoint.sh /usr/app
RUN chmod +x /usr/app/docker-entrypoint.sh
RUN wget -O apm-agent.jar https://search.maven.org/remotecontent?filepath=co/elastic/apm/elastic-apm-agent/1.17.0/elastic-apm-agent-1.17.0.jar
ENTRYPOINT ["./docker-entrypoint.sh"]