FROM bellsoft/liberica-openjdk-alpine
COPY ./urlshortener-0.0.1-SNAPSHOT.jar /usr/app/
RUN chmod +x /usr/app/urlshortener-0.0.1-SNAPSHOT.jar
WORKDIR /usr/app
RUN apk add --no-cache curl tar bash procps nano vim
COPY wait-for-it.sh /usr/app
RUN chmod +x /usr/app/wait-for-it.sh
COPY docker-entrypoint.sh /usr/app
RUN chmod +x /usr/app/docker-entrypoint.sh
ENTRYPOINT ["./docker-entrypoint.sh"]