version: "3"
services:
  db:
    image: couchbase
    deploy:
      replicas: 1
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
  service:
    build: .
    ports:
      - 9090:9090
    depends_on:
      - "db"