version: "3"
services:
  db:
    build: ./couchbase/.
    deploy:
      replicas: 1
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
  app:
    build: ./app/.
    ports:
      - 9090:9090
    entrypoint: ["wait-for-it.sh", "-s" ,"-t", "20", "http://localhost:33615/pools/default", "--"]
    depends_on:
      - "db"