FROM bellsoft/liberica-openjdk-alpine
COPY ./urlshortener-0.0.1-SNAPSHOT.jar /usr/app/
WORKDIR /usr/app
RUN apk add --no-cache curl tar bash procps nano vim
ENTRYPOINT ["java", "-jar", "urlshortener-0.0.1-SNAPSHOT.jar"]